/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.handong.csee.java.inheritance;

public class Animal {
	String name = "Animal";
	
    public static void testClassMethod() {
        System.out.println("The static method in Animal");
    }
	
    public void testInstanceMethod() {
        System.out.println("The instance method in Animal");
    }
}
